"""Единые соглашения по callback_data (Legacy Seller Support)."""

from __future__ import annotations

# Общие
CB_NOOP = "noop"

# Seller: material and payouts history
CB_SELLER_MAT_CAT = "seller:mat:cat"
CB_SELLER_MAT_PAGE = "seller:mat:page"
CB_SELLER_MAT_ITEM = "seller:mat:item"
CB_SELLER_MAT_EDIT = "seller:mat:edit"
CB_SELLER_MAT_DELETE = "seller:mat:delete"
CB_SELLER_MAT_DELETE_CONFIRM = "seller:mat:delete_confirm"
CB_SELLER_MAT_EDIT_MEDIA = "seller:mat:edit_media"
CB_SELLER_MAT_BACK = "seller:mat:back"
CB_SELLER_MAT_FILTER = "seller:mat:filter"
CB_SELLER_PAYHIST_PAGE = "seller:payhist:page"
CB_SELLER_STATS_VIEW = "seller:stats:view"
CB_SELLER_INFO_ROOT = "seller:info:root"
CB_SELLER_INFO_FAQ = "seller:info:faq"
CB_SELLER_INFO_FAQ_P2 = "seller:info:faq_p2"
CB_SELLER_INFO_FAQ_P3 = "seller:info:faq_p3"
CB_SELLER_FAQ_OPEN = "seller:faq:open"
CB_SELLER_INFO_MANUALS = "seller:info:manuals"
CB_SELLER_MANUAL_OPEN = "seller:manual:open"
CB_SELLER_MANUAL_LEVEL = "seller:manual:level"
CB_SELLER_MENU_PROFILE = "seller:menu:profile"
CB_SELLER_MENU_SELL = "seller:menu:sell"
CB_SELLER_MENU_QUICK_ADD = "seller:menu:quick_add"
CB_SELLER_MENU_STATS = "seller:menu:stats"
CB_SELLER_MENU_MATERIAL = "seller:menu:material"
CB_SELLER_MENU_PAYHIST = "seller:menu:payhist"
CB_SELLER_MENU_INFO = "seller:menu:info"
CB_SELLER_MENU_SUPPORT = "seller:menu:support"
CB_SELLER_CANCEL_FSM = "seller:cancel_fsm"
CB_CAPTCHA_START = "captcha:start"
CB_CAPTCHA_CANCEL = "captcha:cancel"
CB_SELLER_FSM_CAT = "seller:fsm:cat"
CB_SELLER_DEPLOY_REPEAT = "seller:deploy:repeat"
