"""add_has_accepted_codex_to_user

Revision ID: 184865767bbf
Revises: 2f7c93ccb319
Create Date: 2026-04-08 04:25:18.593872
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184865767bbf'
down_revision = '2f7c93ccb319'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_accepted_codex', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_accepted_codex')
    # ### end Alembic commands ###
