"""fix_missing_columns_v2

Revision ID: 1ea1301e2caf
Revises: 184865767bbf
Create Date: 2026-04-08 04:38:11.013015
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea1301e2caf'
down_revision = '184865767bbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('pseudonym', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('pin_code', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('is_pin_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('is_incognito', sa.Boolean(), server_default='false', nullable=False))
    
    # Создаем тип Enum вручную, так как Alembic его пропустил
    notification_preference_enum = sa.Enum('full', 'summary', 'none', name='notification_preference_enum')
    notification_preference_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('users', sa.Column('notification_preference', notification_preference_enum, server_default='full', nullable=False))
    op.add_column('users', sa.Column('favorite_categories', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('users', sa.Column('badges', sa.JSON(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'badges')
    op.drop_column('users', 'favorite_categories')
    op.drop_column('users', 'notification_preference')
    op.drop_column('users', 'is_incognito')
    op.drop_column('users', 'is_pin_enabled')
    op.drop_column('users', 'pin_code')
    op.drop_column('users', 'pseudonym')
    op.drop_column('users', 'nickname')
    
    # Удаляем тип Enum
    sa.Enum(name='notification_preference_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
