"""add_composite_index_to_submissions

Revision ID: 2f7c93ccb319
Revises: 58162c168ab8
Create Date: 2026-04-08 04:00:14.922592
"""
from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '2f7c93ccb319'
down_revision = '58162c168ab8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_submissions_status_created_at', 'submissions', ['status', 'created_at'], unique=False)
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS nickname VARCHAR(64)")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS pseudonym VARCHAR(64)")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS pin_code VARCHAR(128)")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS is_pin_enabled BOOLEAN NOT NULL DEFAULT false")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS is_incognito BOOLEAN NOT NULL DEFAULT false")
    
    # Создаем тип Enum вручную через DO блок для надежности в Postgres
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_preference_enum') THEN CREATE TYPE notification_preference_enum AS ENUM ('full', 'summary', 'none'); END IF; END $$;")
    
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS notification_preference notification_preference_enum NOT NULL DEFAULT 'full'")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS favorite_categories JSONB NOT NULL DEFAULT '[]'")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS badges JSONB NOT NULL DEFAULT '[]'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'badges')
    op.drop_column('users', 'favorite_categories')
    op.drop_column('users', 'notification_preference')
    op.drop_column('users', 'is_incognito')
    op.drop_column('users', 'is_pin_enabled')
    op.drop_column('users', 'pin_code')
    op.drop_column('users', 'pseudonym')
    op.drop_column('users', 'nickname')
    op.drop_index('ix_submissions_status_created_at', table_name='submissions')
    # ### end Alembic commands ###
