"""add_composite_index_to_submissions

Revision ID: 2f7c93ccb319
Revises: 58162c168ab8
Create Date: 2026-04-08 04:00:14.922592
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7c93ccb319'
down_revision = '58162c168ab8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_submissions_status_created_at', 'submissions', ['status', 'created_at'], unique=False)
    op.add_column('users', sa.Column('nickname', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('pseudonym', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('pin_code', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('is_pin_enabled', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_incognito', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('notification_preference', sa.Enum('full', 'summary', 'none', name='notification_preference_enum'), nullable=False))
    op.add_column('users', sa.Column('favorite_categories', sa.JSON(), nullable=False))
    op.add_column('users', sa.Column('badges', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'badges')
    op.drop_column('users', 'favorite_categories')
    op.drop_column('users', 'notification_preference')
    op.drop_column('users', 'is_incognito')
    op.drop_column('users', 'is_pin_enabled')
    op.drop_column('users', 'pin_code')
    op.drop_column('users', 'pseudonym')
    op.drop_column('users', 'nickname')
    op.drop_index('ix_submissions_status_created_at', table_name='submissions')
    # ### end Alembic commands ###
