"""optimization_indexes

Revision ID: 780184c2674e
Revises: 21de6377a4ca
Create Date: 2026-04-12 11:45:22.875323
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '780184c2674e'
down_revision = '21de6377a4ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_categories_is_priority'), 'categories', ['is_priority'], unique=False)
    op.create_index(op.f('ix_categories_operator'), 'categories', ['operator'], unique=False)
    op.create_index(op.f('ix_submissions_assigned_at'), 'submissions', ['assigned_at'], unique=False)
    op.create_index(op.f('ix_submissions_reviewed_at'), 'submissions', ['reviewed_at'], unique=False)
    op.create_index('ix_submissions_user_status_created', 'submissions', ['user_id', 'status', 'created_at'], unique=False)
    op.alter_column('users', 'favorite_categories',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('users', 'badges',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.drop_column('users', 'is_pin_enabled')
    op.drop_column('users', 'pin_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pin_code', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_pin_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.alter_column('users', 'badges',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('users', 'favorite_categories',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index('ix_submissions_user_status_created', table_name='submissions')
    op.drop_index(op.f('ix_submissions_reviewed_at'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_assigned_at'), table_name='submissions')
    op.drop_index(op.f('ix_categories_operator'), table_name='categories')
    op.drop_index(op.f('ix_categories_is_priority'), table_name='categories')
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    # ### end Alembic commands ###
