"""add fixed_payout_rate

Revision ID: 8ffa6d92725c
Revises: de3b499ec34a
Create Date: 2026-04-06 16:45:25.837012
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ffa6d92725c'
down_revision = 'de3b499ec34a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('fixed_payout_rate', sa.Numeric(precision=12, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'fixed_payout_rate')
    # ### end Alembic commands ###
