"""add access_pin to users

Revision ID: b64ea96a73bc
Revises: 20260404_0026
Create Date: 2026-04-05 08:22:02.162490
"""
from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = 'b64ea96a73bc'
down_revision = '20260404_0026'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS leaderboard_settings")
    op.execute("ALTER TABLE publication_archives DROP CONSTRAINT IF EXISTS publication_archives_submission_id_key")
    op.execute("DROP INDEX IF EXISTS ix_publication_archives_submission_id")
    op.create_index(op.f('ix_publication_archives_submission_id'), 'publication_archives', ['submission_id'], unique=True)
    op.execute("DROP INDEX IF EXISTS ix_submissions_admin_status")
    op.execute("DROP INDEX IF EXISTS ix_submissions_finalized_at")
    op.execute("DROP INDEX IF EXISTS ix_submissions_finalized_by_admin_id")
    op.execute("DROP INDEX IF EXISTS ix_submissions_status_created_at")
    op.execute("ALTER TABLE submissions DROP CONSTRAINT IF EXISTS fk_submissions_finalized_by_admin_id_users")
    
    # Check if columns exist before dropping them
    # For now, we'll try to drop them via safer SQL or just leave them if they cause issues, 
    # but ALTER TABLE DROP COLUMN doesn't have IF EXISTS in older PG. 
    # Actually PG 9.0+ has IF EXISTS for DROP COLUMN too.
    op.execute("ALTER TABLE submissions DROP COLUMN IF EXISTS final_reason")
    op.execute("ALTER TABLE submissions DROP COLUMN IF EXISTS finalized_by_admin_id")
    op.execute("ALTER TABLE submissions DROP COLUMN IF EXISTS finalized_at")
    op.add_column('users', sa.Column('access_pin', sa.String(length=8), nullable=True, comment='Academy one-time access pin (4-6 digits, nullable)'))
    op.alter_column('users', 'pseudonym',
               existing_type=sa.VARCHAR(length=32),
               comment='Public alias used on the leaderboard only.',
               existing_comment='Public alias used on the leaderboard. NULL = onboarding not completed.',
               existing_nullable=True)
    op.alter_column('users', 'last_deploy_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Cache of last successful eSIM upload: {category_id, label}.',
               existing_nullable=True)
    op.drop_index(op.f('ix_users_pseudonym'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_pseudonym'), 'users', ['pseudonym'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_pseudonym'), 'users', type_='unique')
    op.create_index(op.f('ix_users_pseudonym'), 'users', ['pseudonym'], unique=True)
    op.alter_column('users', 'last_deploy_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Cache of last successful eSIM upload: {category_id, label}.',
               existing_nullable=True)
    op.alter_column('users', 'pseudonym',
               existing_type=sa.VARCHAR(length=32),
               comment='Public alias used on the leaderboard. NULL = onboarding not completed.',
               existing_comment='Public alias used on the leaderboard only.',
               existing_nullable=True)
    op.drop_column('users', 'access_pin')
    op.add_column('submissions', sa.Column('finalized_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('finalized_by_admin_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('final_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_submissions_finalized_by_admin_id_users'), 'submissions', 'users', ['finalized_by_admin_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_submissions_status_created_at'), 'submissions', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_submissions_finalized_by_admin_id'), 'submissions', ['finalized_by_admin_id'], unique=False)
    op.create_index(op.f('ix_submissions_finalized_at'), 'submissions', ['finalized_at'], unique=False)
    op.create_index(op.f('ix_submissions_admin_status'), 'submissions', ['admin_id', 'status'], unique=False)
    op.drop_index(op.f('ix_publication_archives_submission_id'), table_name='publication_archives')
    op.create_index(op.f('ix_publication_archives_submission_id'), 'publication_archives', ['submission_id'], unique=False)
    op.create_unique_constraint(op.f('publication_archives_submission_id_key'), 'publication_archives', ['submission_id'], postgresql_nulls_not_distinct=False)
    op.create_table('leaderboard_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('prize_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('prize_text', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('leaderboard_settings_pkey'))
    )
    # ### end Alembic commands ###
