"""add is_priority to categories

Revision ID: b9138f68e57d
Revises: 13d9df81ab4b
Create Date: 2026-04-06 13:56:10.543031
"""
from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = 'b9138f68e57d'
down_revision = '13d9df81ab4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_assigned_at'), table_name='submissions')
    op.drop_constraint(op.f('uq_users_pseudonym'), 'users', type_='unique')
    op.drop_column('users', 'last_deploy_payload')
    op.drop_column('users', 'pseudonym')
    op.drop_column('users', 'access_pin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_pin', sa.VARCHAR(length=8), autoincrement=False, nullable=True, comment='Academy one-time access pin (4-6 digits, nullable)'))
    op.add_column('users', sa.Column('pseudonym', sa.VARCHAR(length=32), autoincrement=False, nullable=True, comment='Public alias used on the leaderboard only.'))
    op.add_column('users', sa.Column('last_deploy_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Cache of last successful eSIM upload: {category_id, label}.'))
    op.create_unique_constraint(op.f('uq_users_pseudonym'), 'users', ['pseudonym'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_submissions_assigned_at'), 'submissions', ['assigned_at'], unique=False)
    # ### end Alembic commands ###
