"""add_archiving_fields_to_submissions

Revision ID: cd5fbb1d88b9
Revises: 1ea1301e2caf
Create Date: 2026-04-09 09:23:06.750161
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd5fbb1d88b9'
down_revision = '1ea1301e2caf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('submissions', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_submissions_is_archived'), 'submissions', ['is_archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_is_archived'), table_name='submissions')
    op.drop_column('submissions', 'archived_at')
    op.drop_column('submissions', 'is_archived')
    # ### end Alembic commands ###
