"""add is_priority to categories

Revision ID: de3b499ec34a
Revises: b9138f68e57d
Create Date: 2026-04-06 14:46:25.999619
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3b499ec34a'
down_revision = 'b9138f68e57d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_priority', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_priority')
    # ### end Alembic commands ###
